name: Build CocoaInput

on:
  push:
    branches: [ dev/1.20 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Setup git config
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Action"

      - name : Build with Gradle
        run: |
          ./gradlew build --stacktrace
